# Liquid Engine Flight Software Configuration

[system]
name = "Liquid Engine Controller"
version = "1.0.0"
mode = "production"  # development, production, test, maintenance
log_level = "info"   # debug, info, warning, error, critical

[network]
local_ip = "192.168.1.50"
ground_station_ip = "192.168.1.100"
ground_station_port = 2240
telemetry_port = 2241
control_port = 2242
discovery_port = 2243
max_packet_size = 1024
buffer_size = 8192

# Engine Control Configuration
[engine_control]
# Control loop timing
control_frequency_hz = 100
safety_check_frequency_hz = 10
telemetry_frequency_hz = 20

# Engine phases and timeouts
[engine_control.phases]
pre_ignition_timeout_s = 300
ignition_timeout_s = 30
startup_timeout_s = 60
steady_state_timeout_s = 3600
shutdown_timeout_s = 120

# Valve Configuration
[valves]
# Main fuel valve (motor-controlled)
[valves.main_fuel]
type = "motor_controlled"
can_id = "0x101"
min_position = 0.0
max_position = 1.0
default_rate_limit = 0.5  # 1/s
max_rate_limit = 2.0      # 1/s
position_tolerance = 0.01
timeout_ms = 5000

[valves.main_fuel.motor]
kp = 10.0
ki = 1.0
kd = 0.1
integral_limit = 100.0
output_limit = 100.0
max_current = 5.0
max_velocity = 2.0
max_acceleration = 5.0
encoder_resolution = 4096
gear_ratio = 100.0
encoder_inverted = false

# Main oxidizer valve (motor-controlled)
[valves.main_oxidizer]
type = "motor_controlled"
can_id = "0x102"
min_position = 0.0
max_position = 1.0
default_rate_limit = 0.5
max_rate_limit = 2.0
position_tolerance = 0.01
timeout_ms = 5000

[valves.main_oxidizer.motor]
kp = 10.0
ki = 1.0
kd = 0.1
integral_limit = 100.0
output_limit = 100.0
max_current = 5.0
max_velocity = 2.0
max_acceleration = 5.0
encoder_resolution = 4096
gear_ratio = 100.0
encoder_inverted = false

# Igniter fuel valve (solenoid)
[valves.igniter_fuel]
type = "solenoid"
gpio_pin = "GPIO_17"
min_position = 0.0
max_position = 1.0
default_rate_limit = 10.0
max_rate_limit = 50.0
position_tolerance = 0.05
timeout_ms = 1000

# Igniter oxidizer valve (solenoid)
[valves.igniter_ox]
type = "solenoid"
gpio_pin = "GPIO_18"
min_position = 0.0
max_position = 1.0
default_rate_limit = 10.0
max_rate_limit = 50.0
position_tolerance = 0.05
timeout_ms = 1000

# Nitrogen purge valve (solenoid)
[valves.purge_n2]
type = "solenoid"
gpio_pin = "GPIO_19"
min_position = 0.0
max_position = 1.0
default_rate_limit = 10.0
max_rate_limit = 50.0
position_tolerance = 0.05
timeout_ms = 1000

# Cooling water valve (solenoid)
[valves.cooling_h2o]
type = "solenoid"
gpio_pin = "GPIO_20"
min_position = 0.0
max_position = 1.0
default_rate_limit = 10.0
max_rate_limit = 50.0
position_tolerance = 0.05
timeout_ms = 1000

# Gain Scheduling Configuration
[gain_scheduling]
enable_adaptive_scheduling = true
enable_robust_scheduling = true
robustness_factor = 0.8
interpolation_threshold = 0.1
update_rate_hz = 10

# Primary scheduling variables
primary_variables = ["chamber_pressure", "thrust"]

# Secondary scheduling variables
secondary_variables = ["mixture_ratio", "temperature"]

# Thrust control gains
[gain_scheduling.thrust_control]
# Low pressure/low thrust gains
[gain_scheduling.thrust_control.low_pressure]
pressure_breakpoints = [0.0, 1e6, 2e6]  # Pa
thrust_breakpoints = [0.0, 1000.0, 2000.0]  # N
kp_values = [1.0, 2.0, 3.0]
ki_values = [0.1, 0.2, 0.3]
kd_values = [0.01, 0.02, 0.03]

# High pressure/high thrust gains
[gain_scheduling.thrust_control.high_pressure]
pressure_breakpoints = [2e6, 5e6, 10e6]  # Pa
thrust_breakpoints = [2000.0, 5000.0, 10000.0]  # N
kp_values = [3.0, 5.0, 8.0]
ki_values = [0.3, 0.5, 0.8]
kd_values = [0.03, 0.05, 0.08]

# Pressure control gains
[gain_scheduling.pressure_control]
[gain_scheduling.pressure_control.nominal]
pressure_breakpoints = [0.0, 2e6, 5e6, 10e6]  # Pa
kp_values = [0.5, 1.0, 2.0, 3.0]
ki_values = [0.05, 0.1, 0.2, 0.3]
kd_values = [0.005, 0.01, 0.02, 0.03]

# Mixture ratio control gains
[gain_scheduling.mixture_ratio_control]
[gain_scheduling.mixture_ratio_control.nominal]
mixture_ratio_breakpoints = [5.0, 6.0, 7.0, 8.0]  # O/F ratio
kp_values = [2.0, 3.0, 4.0, 5.0]
ki_values = [0.2, 0.3, 0.4, 0.5]
kd_values = [0.02, 0.03, 0.04, 0.05]

# Sensor Configuration
[sensors]
# Pressure transducers
[sensors.pt_chamber]
type = "pressure_transducer"
serial_number = "PT001"
calibration_file = "calibrations/pt_chamber.json"
measurement_range_min = 0.0      # Pa
measurement_range_max = 15e6     # Pa
voltage_range_min = 0.0          # V
voltage_range_max = 5.0          # V
update_rate_hz = 100
enable_calibration = true

[sensors.pt_fuel_inlet]
type = "pressure_transducer"
serial_number = "PT002"
calibration_file = "calibrations/pt_fuel_inlet.json"
measurement_range_min = 0.0
measurement_range_max = 10e6
voltage_range_min = 0.0
voltage_range_max = 5.0
update_rate_hz = 100
enable_calibration = true

[sensors.pt_ox_inlet]
type = "pressure_transducer"
serial_number = "PT003"
calibration_file = "calibrations/pt_ox_inlet.json"
measurement_range_min = 0.0
measurement_range_max = 10e6
voltage_range_min = 0.0
voltage_range_max = 5.0
update_rate_hz = 100
enable_calibration = true

# RTD temperature sensors
[sensors.rtd_chamber_wall]
type = "rtd_temperature"
serial_number = "RTD001"
calibration_file = "calibrations/rtd_chamber_wall.json"
measurement_range_min = -50.0    # °C
measurement_range_max = 500.0    # °C
resistance_range_min = 80.0      # Ohm
resistance_range_max = 200.0     # Ohm
rtd_type = "PT100"
update_rate_hz = 50
enable_calibration = true

[sensors.rtd_fuel_temp]
type = "rtd_temperature"
serial_number = "RTD002"
calibration_file = "calibrations/rtd_fuel_temp.json"
measurement_range_min = -50.0
measurement_range_max = 100.0
resistance_range_min = 80.0
resistance_range_max = 150.0
rtd_type = "PT100"
update_rate_hz = 50
enable_calibration = true

[sensors.rtd_ox_temp]
type = "rtd_temperature"
serial_number = "RTD003"
calibration_file = "calibrations/rtd_ox_temp.json"
measurement_range_min = -50.0
measurement_range_max = 100.0
resistance_range_min = 80.0
resistance_range_max = 150.0
rtd_type = "PT100"
update_rate_hz = 50
enable_calibration = true

# Thermocouples
[sensors.tc_exhaust]
type = "thermocouple"
serial_number = "TC001"
calibration_file = "calibrations/tc_exhaust.json"
measurement_range_min = 0.0      # °C
measurement_range_max = 2000.0   # °C
voltage_range_min = -10.0        # mV
voltage_range_max = 50.0         # mV
tc_type = "Type_K"
update_rate_hz = 50
enable_calibration = true

# IMU sensors
[sensors.imu]
type = "imu"
serial_number = "IMU001"
calibration_file = "calibrations/imu.json"
serial_port = "/dev/ttyUSB0"
baud_rate = 921600
update_rate_hz = 1000
enable_calibration = true

# GPS sensors
[sensors.gps]
type = "gps"
serial_number = "GPS001"
calibration_file = "calibrations/gps.json"
serial_port = "/dev/ttyUSB1"
baud_rate = 115200
update_rate_hz = 10
enable_calibration = true

# Sensor Fusion Configuration
[sensor_fusion]
algorithm = "extended_kalman_filter"
process_noise_variance = 1e-6
measurement_noise_variance = 1e-4
initial_state_uncertainty = 1e-3
enable_outlier_rejection = true
outlier_threshold = 3.0
enable_adaptive_filtering = true
adaptation_rate = 0.01
fusion_frequency_hz = 50

# Calibration Configuration
[calibration]
auto_calibration_enabled = true
calibration_interval_hours = 24
drift_detection_enabled = true
glr_threshold = 0.95
calibration_data_retention_days = 30

# Safety Configuration
[safety]
enable_abort_conditions = true
enable_emergency_shutdown = true
enable_fault_detection = true
max_chamber_pressure = 12e6       # Pa
max_chamber_temperature = 2000.0  # °C
min_mixture_ratio = 4.0           # O/F
max_mixture_ratio = 10.0          # O/F
max_valve_position_error = 0.05   # 5%
max_sensor_age_ms = 1000          # 1 second

# Data Logging Configuration
[logging]
enable_data_logging = true
log_directory = "/var/log/engine_controller"
log_file_max_size_mb = 100
log_file_retention_days = 30
enable_compression = true

[logging.telemetry]
enable_telemetry_logging = true
telemetry_log_frequency_hz = 10
telemetry_compression = true

[logging.events]
enable_event_logging = true
event_log_level = "info"
event_log_retention_days = 90

# Performance Monitoring
[performance]
enable_performance_monitoring = true
performance_log_frequency_hz = 1
enable_real_time_analysis = true
performance_metrics_retention_days = 7

# Hardware Interface Configuration
[hardware]
# CAN bus configuration
[hardware.can]
interface = "can0"
bitrate = 1000000
enable_termination = true

# Serial interface configuration
[hardware.serial]
timeout_ms = 1000
buffer_size = 4096
enable_flow_control = false

# GPIO configuration
[hardware.gpio]
export_on_startup = true
unexport_on_shutdown = true
debounce_time_ms = 50

# Message IDs for communication
[message_ids]
ENGINE_COMMAND = 0x100
VALVE_COMMAND = 0x101
THRUST_COMMAND = 0x102
ABORT_COMMAND = 0x103
ENGINE_STATUS = 0x200
SENSOR_DATA = 0x201
SYSTEM_HEALTH = 0x202
CALIBRATION_STATUS = 0x203
SAFETY_ALERT = 0x300
FAULT_REPORT = 0x301
HEARTBEAT = 0x302
