# ESP32 Serial Communication Configuration
# Configuration file for ESP32 PT sensor integration

[serial]
# Serial port configuration
device_path = "/dev/ttyUSB0"  # Linux: "/dev/ttyUSB0", "/dev/ttyACM0", etc.
                              # Windows: "COM3", "COM4", etc.
                              # macOS: "/dev/cu.usbserial-*", "/dev/cu.usbmodem*"

baud_rate = 115200            # Serial communication baud rate
timeout_ms = 100              # Timeout for serial operations in milliseconds
max_buffer_size = 1024        # Maximum buffer size for incoming data

# Communication mode
enable_binary_mode = true     # true = binary mode (production), false = text mode (debugging)

[pt_sensors]
# PT sensor configuration
max_pt_sensors = 9            # Maximum number of PT sensors (0-8)
max_data_age_ms = 1000.0      # Maximum age of sensor data to include (milliseconds)

# PT sensor location mapping (adjust based on your hardware wiring)
# These map ESP32 ADC channels to engine PT locations
[pt_sensors.location_mapping]
channel_0 = "PRESSURANT_TANK"  # Pressurant Tank PT
channel_1 = "KERO_INLET"       # Kero Inlet PT
channel_2 = "KERO_OUTLET"      # Kero Outlet PT
channel_3 = "LOX_INLET"        # Lox Inlet PT
channel_4 = "LOX_OUTLET"       # Lox Outlet PT
channel_5 = "INJECTOR"         # Injector PT
channel_6 = "CHAMBER_WALL_1"   # Chamber Wall PT #1
channel_7 = "CHAMBER_WALL_2"   # Chamber Wall PT #2
channel_8 = "NOZZLE_EXIT"      # Nozzle Exit PT

[observation_matrix]
# Observation matrix configuration
enable_outlier_detection = true   # Enable outlier detection for sensor data
outlier_threshold_sigma = 3.0     # Outlier threshold in standard deviations
time_sync_tolerance_ms = 50.0     # Time synchronization tolerance (milliseconds)
enable_interpolation = false      # Enable data interpolation for missing sensors
interpolation_window_ms = 100.0   # Window for interpolation (milliseconds)

[logging]
# Logging configuration
log_level = "INFO"               # DEBUG, INFO, WARN, ERROR
enable_console_output = true     # Enable console output
enable_file_logging = false      # Enable file logging
log_file_path = "/var/log/esp32_pt_sensors.log"  # Log file path

[development]
# Development and debugging settings
enable_debug_output = false      # Enable detailed debug output
print_raw_data = false          # Print raw sensor data
print_observation_matrices = false  # Print observation matrices
simulate_missing_sensors = false # Simulate missing sensors for testing
simulate_sensor_delay = false    # Simulate sensor communication delays
